# Site settings
title_left    : "Ilya"
title_right   : "Chikmarev"
description   : "Hello here! I am iOS developer. Explore world with me and be smart!"
keywords      : "Chikmarev, ichikmarev, iOS"
url           :  # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

twitter_username  : "ichikmarev"
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Ilya Chikmarev"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
